version: '3'

services:
  mlflow-server:
    image: mlflow_project_mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_SERVER_FILESTORE=/mlflow_server

  trainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python train.py

